### ISSUE TITLE
Language support for Polish

### ISSUE THREAD

**Issue by sebrock** [sebrock/bananominer-watch-DEV_TEST#40]
There was a comment by a Polish guy volunteering to make Polish translation under [this publish0x article](https://www.publish0x.com/banano/earning-dollar-ban-with-bananominer-check-out-bananominer-wa-xzypwqd)

![image](https://user-images.githubusercontent.com/156824/89525785-07699a80-d7e7-11ea-85bc-0c5edbfa9019.png)

- [x] Recruit translator
- [x] Add Polish to [POEditor](https://poeditor.com/projects/view?id=352441)
- [x] Invite translator
- [x] Track and collect translation
- [x] Extract translation and beautify messages.json
- [x] Add messages.json to repo
- [x] Include in next release
- [x] Edit webstore local page

**Comment by sebrock** [comment]
Update: Still no message from the guy :(
![image](https://user-images.githubusercontent.com/156824/89525842-1bad9780-d7e7-11ea-9e8c-a097bd0f1b98.png)

**Comment by sebrock** [comment]
recruited imalfect from https://faucet.imalfect.xyz/

**Comment by imalfect** [comment]
I'm here! Translating using the link you provided me!

**Comment by sebrock** [comment]
included in release https://github.com/sebrock/bananominer-watch-DEV_TEST/releases/tag/1.3.8a
