### ISSUE TITLE
Align date and date/time formats

### ISSUE THREAD

**Issue by sebrock** [sebrock/bananominer-watch-DEV_TEST#44]
Dates /timestamps are displayed in different formats.
Make them all like **YYYY-MM-DD / YYYY-MM-DD HH:MM:SS (24h)**

![image](https://user-images.githubusercontent.com/156824/89517367-e51d5000-d7d9-11ea-9033-2bcd86697852.png)

**Comment by andrecrjr** [comment]
is just to do the same in the work unit upside in refresh time?

**Comment by sebrock** [comment]
> is just to do the same in the work unit upside in refresh time?

All like _last WU_(marked in pink)

**Comment by sebrock** [comment]
The account created still has a different format.
Suggest to convert to string and truncate to only show the date (10 chars) , time is not too relevant
![image](https://user-images.githubusercontent.com/156824/112765453-91cc6c00-900d-11eb-815c-2d5c4678c729.png)

**Comment by sebrock** [comment]
@heanzyzabala something for you?

**Comment by andrecrjr** [comment]
lol forgot that one lemme see if I can change it

**Comment by heanzyzabala** [comment]
@sebrock Done. https://github.com/sebrock/bananominer-watch-DEV_TEST/pull/74

**Comment by sebrock** [comment]
Thanks @heanzyzabala
