### ISSUE TITLE
Add USD value of earned BAN

### ISSUE THREAD

**Issue by sebrock** [sebrock/bananominer-watch-DEV_TEST#47]
- [x] Find best source for exchange rate (coingecko API?)
- [x] Calculation
- [x] Display

**Comment by andrecrjr** [comment]
coingecko is easy

**Comment by sebrock** [comment]
API call is
### [https://api.coingecko.com/api/v3/coins/banano?localization=true&tickers=true](https://api.coingecko.com/api/v3/coins/banano?localization=true&tickers=true)

Required data for calculation:
"market_data": {
"current_price": {"usd": 0.00103666,}}

**Comment by heanzyzabala** [comment]
Hi All. Please review: https://github.com/sebrock/bananominer-watch-DEV_TEST/pull/66

**Comment by sebrock** [comment]
Nice! 
Can you round the USD value to 2 decimals please?

Also, if you could do the same for the BAN earned that would look much sleeker.

thanks!

![image](https://user-images.githubusercontent.com/156824/112623306-7b1aef00-8e2c-11eb-999e-7cd9bd2d5758.png)
