### ISSUE TITLE
Include links to download Certificates

### ISSUE THREAD

**Issue by sebrock** [sebrock/bananominer-watch-DEV_TEST#49]
Foldingathome provides a URL to generate and download Certificates of Completion for each user.
These state the number of completed WUs or Points (both rounded), respectively.

Lets include links to both of these within [/scripts/components/renderTop/index.js](/scripts/components/renderTop/index.js)

The argument to be passed for a specific user is the `id` returned from
`https://stats.foldingathome.org/api/donor/[donorname]`

```
{
"wus": 2839,
"rank": 106780,
"total_users": 2764662,
"active_50": 2,
"path": "donor/iywv3nzbitk7",
"wus_cert": "https://apps.foldingathome.org/awards?user=83904266&type=wus",
"id": 83904266,
"credit_cert": "https://apps.foldingathome.org/awards?user=83904266&type=score",
"last": "2020-11-01 23:44:31",
"name": "iywv3nzbitk7",
"teams": [
{
"wus": 2839,
"last": "2020-11-01 23:44:31",
"uid": 83904266,
"active_50": 2,
"active_7": 2,
"credit": 5834688,
"team": 234980,
"name": "www.banano.cc"
}
],
"active_7": 2,
"credit": 5834688
}

```

 ## WUs certificate

Call: 

`https://apps.foldingathome.org/awards?user=[id]&type=wus`

![20201101_FoldingAtHome-wus-certificate-83904266](https://user-images.githubusercontent.com/156824/97847972-b76c7800-1cf0-11eb-9e54-94808dd112b1.jpg)

 ## Points certificate

Call: 

`https://apps.foldingathome.org/awards?user=[ID]`

![20201101_FoldingAtHome-points-certificate-83904266](https://user-images.githubusercontent.com/156824/97848034-ce12cf00-1cf0-11eb-9abc-63f2ef5b5935.jpg)

**Comment by andrecrjr** [comment]
i put a hamburguer menu in the top, i think it would work better with these links and new ones in the future maybe, can test in the develop branch

**Comment by sebrock** [comment]
Nice! I see the links.

![image](https://user-images.githubusercontent.com/156824/100987167-744f3000-354e-11eb-942c-742de133a5fe.png)


**BUT:** The "Credit" links gives the WU certificate.
Also: 
I would prefer the names of the links to be linke this:
~~Work Unit Certificate~~ **Certificate (Work Units)**
~~Credit Certificate~~ **Certificate (Points)**

**Comment by sebrock** [comment]
Changes made. 
Still unsolved: Both the "WU" AND the "Credit" links gives the WU certificate.

**Comment by sebrock** [comment]
Points certificate still not working.

See https://github.com/FoldingAtHome/fah-issues/issues/1413

Related foldingathome forum post: [https://foldingforum.org/viewtopic.php?f=16&t=36655&p=347713&hilit=certificate#p347712](https://foldingforum.org/viewtopic.php?f=16&t=36655&p=347713&hilit=certificate#p347712)

**Comment by heanzyzabala** [comment]
Closing this. Issue has been fixed here: https://github.com/sebrock/bananominer-watch-DEV_TEST/issues/60https://github.com/sebrock/bananominer-watch-DEV_TEST/issues/60
