### ISSUE TITLE
Language support for Serbian (sr)

### ISSUE THREAD

**Issue by sebrock** [sebrock/bananominer-watch-DEV_TEST#53]
[Link to translations in POEditor ](https://poeditor.com/projects/po_edit?id_language=213&per_page=20&id=352441)

- [x] Recruit translator
- [x] Add Serbian to [POEditor](https://poeditor.com/projects/view?id=352441)
- [x] Invite translator
- [x] Track and collect translation
- [x] Extract translation and beautify messages.json
- [x] Add messages.json to repo
- [x] Include in next release
- [x] Edit webstore local page

**Comment by sebrock** [comment]
messages.json file committed https://github.com/sebrock/bananominer-watch-DEV_TEST/commit/d9c99d34995f04329bd0aa0f87292024b23b23e9

**Comment by sebrock** [comment]
Including in release V1.3.3

**Comment by kylelondon92** [comment]
Partial missing translation detected on Chrome Web Store.

Text is partially translated and partially still in English. Please check translations submitted to correct this.
![issue53_001](https://user-images.githubusercontent.com/74376668/99757675-3256d080-2af0-11eb-8374-5b89288b9165.png)

**Comment by kylelondon92** [comment]
The "Your user ID" field placeholder is only partially visible and unclear to people who might not know what are they exactly supposed to supply in the input field.
![issue53_002](https://user-images.githubusercontent.com/74376668/99757936-c45ed900-2af0-11eb-9742-72cfd1bbf2b6.png)

**Comment by kylelondon92** [comment]
Another partial translation detected after setting the mining ID.
![issue53_003](https://user-images.githubusercontent.com/74376668/99758129-359e8c00-2af1-11eb-9b17-16315dc05518.png)

**Comment by kylelondon92** [comment]
Unable to take the exact screenshot of this issue due to it's nature. It is related to top headers visible in the image bellow. Once you hover over these, additional text slides down and becomes visible regarding PPD calc and team stats. Text that is comming in is also not translated, and is in English.
![issue53_004](https://user-images.githubusercontent.com/74376668/99758308-9af27d00-2af1-11eb-94fe-3dc0a99830cf.png)

**Comment by kylelondon92** [comment]
Additionally, the extension layout seems to get broken after the remove (trash bin) icon is clicked. I am not sure if that is intentional or a bug itself. See the image bellow. Additionally if I forgot to check certain extension parts, let me know.
![issue53_005](https://user-images.githubusercontent.com/74376668/99758518-384db100-2af2-11eb-8700-7da47485ed9d.png)

**Comment by sebrock** [comment]
> Partial missing translation detected on Chrome Web Store.
> 
> Text is partially translated and partially still in English. Please check translations submitted to correct this.
> ![issue53_001](https://user-images.githubusercontent.com/74376668/99757675-3256d080-2af0-11eb-8374-5b89288b9165.png)

This is rooted in the fact that the final step of this issue **_Edit webstore local page_** has not been completed yet. 
The localized Long description text on the webstore can only be adapted from the defaulted English version AFTER the new release was accepted and listed.

It is done now.
The credits however had to be removed (from the English version initially) because they supposedly are not in line with webstore policies. Therefore I have changed this part to 

```
Credits
Our sincere thanks go to everyone in the BANANO community who contributed and supported in the making of this. BAN fam - best fam! 💛

For Translation and Proofreading credits, please go to https://sebrock.github.io/bananominer-watch-DEV_TEST/.
Google has rejected the latest release because of the credits.
```

@kylelondon92  Appreciate if you could give me a Serbian version of that! (as another reply here).

**Comment by sebrock** [comment]
> Another partial translation detected after setting the mining ID.
> ![issue53_003](https://user-images.githubusercontent.com/74376668/99758129-359e8c00-2af1-11eb-9b17-16315dc05518.png)

_Score_  has not been translated on purpose (since it is the f@h term, as opposed to Points e.g.)
