### ISSUE TITLE
The "Your user ID" field placeholder is only partially visible and unclear to people who might not know what are they exactly supposed to supply in the input field.

### ISSUE THREAD

**Issue by sebrock** [sebrock/bananominer-watch-DEV_TEST#56]
The "Your user ID" field placeholder is only partially visible and unclear to people who might not know what are they exactly supposed to supply in the input field.
![issue53_002](https://user-images.githubusercontent.com/74376668/99757936-c45ed900-2af0-11eb-9742-72cfd1bbf2b6.png)

_Originally posted by @kylelondon92 in https://github.com/sebrock/bananominer-watch-DEV_TEST/issues/53#issuecomment-730836618_

**Comment by sebrock** [comment]
@andrecrjr Can the field length be changed to the length of the translated string?

**Comment by andrecrjr** [comment]
by default the placeholder can't define the input's length, but i can research it better using javascript!

**Comment by sebrock** [comment]
> by default the placeholder can't define the input's length, but i can research it better using javascript!

Alternatively it could be the maximum length there is of the 
```
"yourUser": {
        "message": "Deine User ID:"
 },
```
message in all of the the `messages.json`
in [/_locales/](https://github.com/sebrock/bananominer-watch-DEV_TEST/tree/master/_locales)

**Comment by sebrock** [comment]
> > by default the placeholder can't define the input's length, but i can research it better using javascript!
> 
> Alternatively it could be the maximum length there is of the
> 
> ```
> "yourUser": {
>         "message": "Deine User ID:"
>  },
> ```
> 
> message in all of the the `messages.json`
> in [/_locales/](https://github.com/sebrock/bananominer-watch-DEV_TEST/tree/master/_locales)

..which is **30 characters** in Farsi:
![image](https://user-images.githubusercontent.com/156824/100742163-a049a480-33da-11eb-9a4a-352745c858e5.png)

**Comment by andrecrjr** [comment]
i will get the placeholder lenght and multiply by 10 and put in the width... this can be work.

**Comment by andrecrjr** [comment]
i put a default "320px" width on input in the develop branch, can be tested, is a bit hard to define the width base just by the placeholder character's length each word is different in size

**Comment by sebrock** [comment]
> i put a default "320px" width on input in the develop branch, can be tested, is a bit hard to define the width base just by the placeholder character's length each word is different in size

320 px seems about right to fit 30 characters.

![image](https://user-images.githubusercontent.com/156824/100855168-2d980200-348a-11eb-86e7-fa7defbcbc02.png)

I also like the hamburger menu on the upper right.
I think this is where also the links to the certificates should be #49
