### ISSUE TITLE
Users have reported that the extension is not working anymore

### ISSUE THREAD

**Issue by sebrock** [sebrock/bananominer-watch-DEV_TEST#63]
**Describe the bug**
Reportedly, users are getting the `errNotfound` error for any user ID being entered.
https://github.com/sebrock/bananominer-watch-DEV_TEST/blob/286fcc430ae2d1bd1ec9294b03b62616fa9bf74c/scripts/components/renderUser/fetchBananoMiner.js#L40

**To Reproduce**
1. Click extension icon
2. Enter user ID
3. Click on 'find'
3. See error

**Expected behavior**
Display user stats or throw 'inactive' error

**Screenshots**
![image](https://user-images.githubusercontent.com/156824/107139893-ccbff680-691e-11eb-8570-68602154ffd4.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: chrome
 - Version: any

**Comment by sebrock** [comment]
**Root cause analysis**
Root cause likely to be the limitations having been imposed on the CORS-Anywhere demo .
See https://github.com/Rob--W/cors-anywhere/issues/301

**Comment by sebrock** [comment]
Just removing CORS does not help. 
Now getting this error in the extension console:
![image](https://user-images.githubusercontent.com/156824/107140528-f11dd200-6922-11eb-84b0-67eefad50cf2.png)

How to set the mode of the request to `no-cors`?

**Comment by andrecrjr** [comment]
it will need to go on the fetch function and

` fetch("...api", {mode:"no-cors"}) ` 

but personally i don't think this will help

Some of other url proxies: https://nordicapis.com/10-free-to-use-cors-proxies/

But the real good sollution maybe f@h release CORS on their side 😢  I don't know why they release an API that breaks... but until they dont release we need to use url proxy sollutions...

**Comment by andrecrjr** [comment]
https://foldingforum.org/viewtopic.php?f=61&t=33021

it seems stats.foldingathome.org is deprecated, and they are using this one: https://api.foldingathome.org/

Altough it's a new API, it has the same CORS problem...

The only way I think we need to deploy our own cors proxy server(just clone [cors-anywhere](https://github.com/Rob--W/cors-anywhere) and deploy) for us.

**Comment by heanzyzabala** [comment]
Hi all. Created a PR for this: https://github.com/sebrock/bananominer-watch-DEV_TEST/pull/64

**Comment by sebrock** [comment]
#65 by @heanzyzabala provides a temporary workaround for cases, where active accounts, which did not receive due payments were shown as inactive.
