### ISSUE TITLE
F@H API returns 502 bad gateway

### ISSUE THREAD

**Issue by heanzyzabala** [sebrock/bananominer-watch-DEV_TEST#72]
**Describe the bug**
F@H API returns 502 bad gateway

**To Reproduce**
1. GET https://stats.foldingathome.org/api/donor/${user}

**Expected behavior**
Returns user details

**Additional context**
Not sure if it's a temporary error and will fix itself soon. Will have to check again later.
Additionally, since https://stats.foldingathome.org is planned to be deprecated soon, we may need to migrate to https://api.foldingathome.org and adjust some logic.

**Comment by heanzyzabala** [comment]
It seems to work again now.

**Comment by sebrock** [comment]
> It seems to work again now.

Thanks for reporting tho-

**Comment by sebrock** [comment]
`This API is deprecated. Some functionality may be available temporarily via the statsclassic.foldingathome.org domain. Going forward statistics should be retrieved from api2.foldingathome.org.`
