### ISSUE TITLE
Revamp theme to match official bananominer website

### ISSUE THREAD

**Issue by heanzyzabala** [sebrock/bananominer-watch-DEV_TEST#79]
**Description**

Can we update the theme to match https://bananominer.com?

![Screen Shot 2021-06-04 at 2 17 31 PM](https://user-images.githubusercontent.com/16485014/120754686-9b0f1300-c53f-11eb-9245-751fd6284e31.png)

**Comment by sebrock** [comment]
sure why not.
feel free to give it a go

**Comment by sebrock** [comment]
Done with commit https://github.com/sebrock/bananominer-watch-DEV_TEST/commit/2545a8e0b5a780f95366ce87837b7f5f64f73a71

![image](https://user-images.githubusercontent.com/156824/130641814-29ab2523-530e-4b45-ac0a-149e04469b75.png)

@heanzyzabala what do you think?
